Ensure that `PSM_USER` and `PSM_PASSWORD` are set in your environment

```python
import time
import os
import {{libName}}
import {{libName}}.{{{packageName}}}
from {{libName}}.{{packageName}}.{{apiPackage}} import {{classVarName}}
from {{libName}}.{{packageName}}.models.{{group}} import *
{{#imports}}
{{{.}}}
{{/imports}}
from pprint import pprint
from dateutil.parser import parse as dateutil_parser
{{> python_doc_auth_partial}}
# Enter a context with an instance of the API client
with {{libName}}.{{{packageName}}}.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = {{classVarName}}.{{{classname}}}(api_client)
{{#requiredParams}}
{{^defaultValue}}
    {{paramName}} = {{{example}}} # {{{dataType}}} | {{{description}}}
{{/defaultValue}}
{{/requiredParams}}
{{#optionalParams}}
    {{paramName}} = {{{example}}} # {{{dataType}}} | {{{description}}}{{^required}} (optional){{/required}}{{#defaultValue}} if omitted the server will use the default value of {{{defaultValue}}}{{/defaultValue}}
{{/optionalParams}}

    # example passing only required values which don't have defaults set
    try:
{{#summary}}
        # {{{.}}}
{{/summary}}
        {{#returnType}}api_response = {{/returnType}}api_instance.{{{operationId}}}({{#requiredParams}}{{^defaultValue}}{{paramName}}{{^-last}}, {{/-last}}{{/defaultValue}}{{/requiredParams}})
{{#returnType}}
        pprint(api_response)
{{/returnType}}
    except {{libName}}.{{{packageName}}}.ApiException as e:
        print("Exception when calling {{classname}}->{{operationId}}: %s\n" % e)

```
